site_name: Software Engineering Handbook
site_description: Software Engineering Handbook

repo_url: https://github.com/anujonthemove/Software-Engineering-Handbook
repo_name: anujonthemove/Software-Engineering-Handbook


# Configuration
theme:
  name: material
  font:
    text: Epilogue
    code: Roboto Mono
    language: en
  # favicon: images/favicon.ico
  # logo: assets/logo.png

  features:
    - navigation.top
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.indexes
    
    
    # - navigation.tracking
    # - navigation.tabs.sticky

    - content.tabs.link
    - content.code.copy
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/regular/bookmark
      info: octicons/info-16
      tip: material/fire
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: octicons/zap-16
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    
  palette:
    primary: black
    accent: orange


plugins:
  - glightbox
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'


markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - admonition
  - admonition
  - pymdownx.details


extra_css:
  - stylesheets/asciinema-player.css
  # - stylesheets/extra.css

extra_javascript:
  - javascripts/asciinema-player.min.js

extra:
  analytics:
    provider: google
    property: G-Q2NX3Z3Y9P


# Site navigation
nav:
  - Home: 'index.md'
  - Python Machine Learning Template:
    - python-machine-learning-template/index.md
    - Process Flow: 'python-machine-learning-template/process-flow.md'
    - Prerequisites: 'python-machine-learning-template/prerequisites.md'
    - Project Setup: 'python-machine-learning-template/project-setup.md'
    - Pipenv: 'python-machine-learning-template/pipenv.md'
    - .env: 'python-machine-learning-template/dot-env.md'
    - pre-commit: 'python-machine-learning-template/pre-commit.md'
    - setup.py: 'python-machine-learning-template/setup.py.md'
    - Loading Files in Python Projects: 'python-machine-learning-template/loading-files-in-python-projects.md'
    - .gitattributes: 'python-machine-learning-template/gitattributes.md'
    - tox.ini: 'python-machine-learning-template/tox.md'
    - workspaces: 'python-machine-learning-template/workspaces.md'
    - faqs: 'python-machine-learning-template/faqs.md'
  - IDE:
    - ide/vs-code.md
  # - Version Control:
  #   - version-control/git-flow-model.md